version: '{build}'

os: Visual Studio 2015

environment:
  matrix:
  - Toolset: v140
#  - Toolset: v120
#  - Toolset: v110
#  - Toolset: v100

platform:
  - Win32
#  - x64

configuration:
#  - Release
  - Debug

build:
  verbosity: minimal

before_build:
- ps: |
    Write-Output "Configuration: $env:CONFIGURATION"
    Write-Output "Platform: $env:PLATFORM"
    $generator = switch ($env:TOOLSET)
    {
        "v140" {"Visual Studio 14 2015"}
        "v120" {"Visual Studio 12 2013"}
        "v110" {"Visual Studio 11 2012"}
    }
    if ($env:PLATFORM -eq "x64")
    {
        $generator = "$generator Win64"
    }
    $xamarin = switch ($env:TOOLSET)
    {
        "v140" {"C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"}
        "v120" {"C:\Program Files (x86)\MSBuild\12.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"}
        "v110" {"C:\Program Files (x86)\MSBuild\11.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"}
    }
    del "$xamarin"

build_script:
- ps: |
    md _build -Force | Out-Null
    cd _build
    & cmake -G "$generator" -DCMAKE_CONFIGURATION_TYPES="Debug;Release" ..
    if ($LastExitCode -ne 0) {
        throw "Exec: $ErrorMessage"
    }
    & cmake --build . --config $env:CONFIGURATION
    if ($LastExitCode -ne 0) {
        throw "Exec: $ErrorMessage"
    }

test_script:
- ps: |
    & ctest -C $env:CONFIGURATION --output-on-failure
    if ($LastExitCode -ne 0) {
        throw "Exec: $ErrorMessage"
    }
